# PyTorch
In this exercise, we will look at some basic functionality of PyTorch. Your are free to use other DL frameworks for your exercises and your project. However, the master solutions and code examples will be in PyTorch.

The [PyTorch documentation](https://pytorch.org/docs/stable/index.html) offers information on its functionality. A lot of the time, your specific question will also have been asked on the [PyTorch Forum](https://discuss.pytorch.org/), often with competent answers by the core developers (Google will find the relevant thread for you).

First, we have to install PyTorch. We will install the basic version for this exercise. For your project, if you want to run on a GPU, you'll have to make sure to have a PyTorch version installed that is compatible with the CUDA version of your NVIDIA drivers. PyTorch has an [installation guide](https://pytorch.org/get-started/locally/) that will help you with getting the right version.

In [13]:
%pip install -q torch ipywidgets ipykernel

Note: you may need to restart the kernel to use updated packages.


In [14]:
import torch

## Tensor operations
Most of PyTorch's operations have the same name as in NumPy. The basic object for storing data is the `torch.tensor`, the equivalent of the `np.array`. With the help of the [Tensor tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html), do the following:

- Create a `torch.tensor` with the elements `[[1, 2], [3, 4]]`
- Create a tensor of ones/zeros with the same shape and dtype
- Create a random tensor of the same shape
- Print the tensor's shape, data type and device
- Try to move it to the GPU
- For Mac users: Try to move it to [MPS](https://pytorch.org/docs/stable/notes/mps.html)
- Check out indexing/slicing operations, and how you can assign values to a slice.
- Combine tensors with `torch.cat` and `torch.stack`. What are the differences?
- Multiply tensors, element-wise and with matrix multiplication.

In [39]:
t1 = torch.tensor(
    [[1, 2], [3, 4]]
)

t2 = torch.tensor(
    [[0, 1], [1, 0]]
)

t3 = torch.rand(
    2, 2
)

tensors = [t1, t2, t3]

for tensor in tensors:
    print(tensor.shape)
    print(tensor.dtype)
    print(tensor.device)
    print("\n")

t1[:, 1]
t2[0,1] = 2
print(t1)
print(t2)

torch.Size([2, 2])
torch.int64
cpu


torch.Size([2, 2])
torch.int64
cpu


torch.Size([2, 2])
torch.float32
cpu


tensor([[1, 2],
        [3, 4]])
tensor([[0, 2],
        [1, 0]])


In [16]:
if torch.cuda.is_available():
    print("available")
else:
    print("not available :c")

not available :c


In [46]:
cat = torch.cat((t1, t2))
print(cat)
cat.dim_order()

tensor([[1, 2],
        [3, 4],
        [0, 2],
        [1, 0]])


(0, 1)

In [47]:
stack = torch.stack((t1,t2))
print(stack)
stack.dim_order()

tensor([[[1, 2],
         [3, 4]],

        [[0, 2],
         [1, 0]]])


(0, 1, 2)

In [ ]:
t1 * t2

tensor([[0, 4],
        [3, 0]])

In [ ]:
t1 @ t2

tensor([[2, 2],
        [4, 6]])

## Neural Network Basics
Solve the followings tasks with the help of the [Neural networks tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html).

The `nn.Module` is the basic class for layers, networks and models. All parameters of an `nn.Module` are automatically discovered by PyTorch and updated by back-propagation.

First, define a neural network (as a subclass of `nn.Module`) with two linear layers and a ReLU non-linearity in between. Make the input, output, and inner dimensions parameters of your network.

In [17]:
import torch.nn as nn

In [30]:
class Net(nn.Module):
    def __init__(self, input_dim=42, hidden_dim=69, output_dim=420):
        super().__init__()
        self.l1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, input):
        x1 = self.l1(input)
        x2 = self.relu(x1)
        x3 = self.l2(x2)
        return x3
    
net = Net()

Move the entire network to the GPU/MPS.

In [ ]:
if torch.cuda.is_available():
    net.to("cuda") 
else:
    print("No cuda :c")

No cuda :c


Print the parameters of your network.

In [20]:
net = Net()
print(list(net.parameters()))

[Parameter containing:
tensor([[-0.1173, -0.0636,  0.0839,  ..., -0.0501,  0.0694,  0.0562],
        [-0.1062, -0.1321,  0.1382,  ..., -0.0961, -0.0302, -0.0874],
        [ 0.1119,  0.1325, -0.0162,  ..., -0.0386,  0.0185, -0.0480],
        ...,
        [ 0.1296, -0.0766, -0.1163,  ..., -0.1138,  0.0304,  0.0257],
        [ 0.0700,  0.1481, -0.0364,  ...,  0.0451, -0.0340, -0.0119],
        [ 0.1304, -0.1337, -0.0668,  ...,  0.0856, -0.0270, -0.0366]],
       requires_grad=True), Parameter containing:
tensor([-0.1088, -0.0842,  0.1162, -0.0688, -0.0426,  0.0655,  0.1444,  0.0091,
         0.0975,  0.0960, -0.0263,  0.0277,  0.0795,  0.0582, -0.1066, -0.0848,
        -0.1236,  0.0227, -0.1385, -0.0963, -0.1042, -0.1020, -0.0684, -0.0124,
         0.1133, -0.1510, -0.0190,  0.1389, -0.1396, -0.1504, -0.0626,  0.0106,
        -0.0655, -0.0706, -0.1084, -0.0773, -0.1262, -0.0145,  0.0003, -0.0262,
         0.0832,  0.1325,  0.0846, -0.0577, -0.1028,  0.0644,  0.0820, -0.0240,
        -0.06

Run a single forward-pass with a random input.

In [21]:
net(torch.rand(42))

tensor([-3.1657e-02,  2.5733e-01,  6.5505e-02, -1.1211e-01,  2.6125e-01,
         1.1152e-01, -3.7310e-01, -4.4060e-02,  3.3794e-02,  2.4972e-01,
         1.2857e-02,  2.6614e-01, -4.6346e-02,  2.5126e-01,  2.4274e-01,
         2.9480e-02,  4.9472e-02, -3.4511e-03,  1.9583e-01, -1.9294e-01,
         1.8043e-01, -8.6961e-03, -9.4013e-02, -1.3898e-01, -5.9385e-02,
         2.7545e-01,  1.4080e-02,  2.3374e-01,  3.6135e-02,  2.1742e-02,
        -2.9522e-01,  1.8420e-01, -1.1701e-01,  1.0689e-01,  1.3421e-01,
        -1.1738e-01,  5.0857e-02, -1.4619e-01,  7.3451e-02, -8.6208e-02,
        -1.8043e-01,  4.9258e-02, -5.7542e-02, -1.2602e-01, -1.8038e-01,
        -1.8335e-01,  2.0654e-01,  4.8926e-02,  2.8205e-01,  3.3751e-02,
        -2.5410e-01, -2.1863e-01, -5.2265e-02, -4.2655e-01,  4.8524e-02,
        -3.8355e-02, -2.3820e-01, -1.6672e-01, -1.4313e-01, -1.8795e-01,
         1.4624e-01,  2.0739e-01, -6.0322e-02,  7.9473e-03,  2.7885e-01,
        -8.3263e-02,  1.7484e-02,  1.7602e-01,  8.3

Define a `nn.MSELoss` and a random target.

In [22]:
output = net(torch.rand(42))
target = torch.randn(420)
criterion = nn.MSELoss()

Compute the loss and run backpropagation.

In [23]:
loss = criterion(output, target)
print(loss)

print(net.l1.bias.grad)

net.zero_grad()
print(net.l1.bias.grad)

loss.backward()
print(net.l1.bias.grad)

tensor(1.0332, grad_fn=<MseLossBackward0>)
None
None
tensor([ 0.0000,  0.0000, -0.0038,  0.0000,  0.0084,  0.0000,  0.0020, -0.0007,
         0.0077, -0.0018,  0.0000,  0.0011,  0.0076,  0.0000,  0.0000,  0.0000,
         0.0000, -0.0057, -0.0042, -0.0027, -0.0004,  0.0047,  0.0076,  0.0046,
         0.0000,  0.0055,  0.0014,  0.0038, -0.0053,  0.0000,  0.0028,  0.0097,
         0.0000, -0.0038,  0.0000,  0.0069,  0.0000,  0.0000, -0.0091, -0.0002,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0058,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0260,  0.0078,  0.0003,  0.0128,  0.0000,  0.0000, -0.0053,
        -0.0047,  0.0068,  0.0000,  0.0034,  0.0000])


Update the parameters of your network with a learning rate of 0.01.

In [24]:
learning_rate = 0.01
for p in net.parameters():
    p.data.sub_(p.grad.data * learning_rate)

Use the `AdamOptimizer` instead to update your parameters (see the [torch.optim documentation](https://pytorch.org/docs/stable/optim.html)).

In [27]:
import torch.optim as optim

optimizer = optim.Adam(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(torch.rand(42))
loss = criterion(output, target)
loss.backward()
optimizer.step()
